# Generated by Django 6.0.5 on 2026-05-17 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_userprofile_plan_type_userprofile_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='courses.course'),
        ),
    ]
