# Generated by Django 6.0.5 on 2026-05-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_studysession_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_exam_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='passed_exam',
            field=models.BooleanField(default=False),
        ),
    ]
