# Generated by Django 6.0.4 on 2026-05-22 04:14

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_last_exam_attempt_course_passed_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.avatar_upload_path),
        ),
    ]
