# Generated by Django 6.0.5 on 2026-05-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_color',
            field=models.CharField(default='red', max_length=20),
        ),
    ]
